### ISSUE TITLE
Plugin doesn't work, seems not to start

### ISSUE THREAD

**Issue by progi-specjalizacje** [alima-webdev/zotero-article-status#9]
The plugin just doesn't work
In the library `Status` column is not visible, and can't be found in `view` > `columns` dropdown. Context menu after right-clicking element in the library doesn't contain `article status` visible in the video on github page. 
![image](https://github.com/user-attachments/assets/365a7d80-b2c2-4639-9a78-221f8432324d)

I have installed plugin from file version 1.0.4 (other plugins work correctly), i vae also tried with version  1.0.3 and got the same result. I have turned off all the other plugins for debugging purpose, i am running newest Zotero 7 on Windows 10

maybe i screwed up during installation, README.MD says:
> "To install the plugin, simply download the latest release from the Releases section and follow the installation instructions provided in the README file." 

but there is no further information on how to run it.

Please contact me if you need any additional info. I would be grateful for your help, you plugin seems super useful but i can't get it to work.

**Comment by progi-specjalizacje** [comment]
after two weeks i've noticed that plugin suddenly started working, i can't recall installing any new update or anything else that may have casued it. IDK what have have changed, but i am happy that it works :)

**Comment by alima-webdev** [comment]
I am glad the plugin is working for you now
